### ISSUE TITLE
About functions

### ISSUE THREAD

**Issue by Deshiba** [mJehanno/cr-tips#8]
The links in the about section do nothing.

**Comment by mJehanno** [comment]
Will work on this section before release an official version but I keep that for later

**Comment by mJehanno** [comment]
Will probably be resolved with #15

**Comment by mJehanno** [comment]
need to add the following : "This is unofficial content and is not approved, sponsored or endorsed by, or affiliated with, Tencent in any way. Any Chess Rush trademarks or copyrights included in this content are the sole property of Tencent."
